# HANDWRITTEN DIGIT CLASSIFICATION USING MNIST DATASET 

In [40]:

from numpy.random import seed
seed(888)
import tensorflow as tf
tf.random.set_seed(404)

In [41]:
import os
import numpy as np
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

# Constants

In [42]:
X_TRAIN_PATH='MNIST/digit_xtrain.csv'
X_TEST_PATH='MNIST/digit_xtest.csv'
Y_TRAIN_PATH='MNIST/digit_ytrain.csv'
Y_TEST_PATH='MNIST/digit_ytest.csv'

NR_CLASSES=10
VALIDATION_SIZE=10000

IMAGE_HEIGHT=28
IMAGE_WIDHT=28
CHANNELS=1

TOTAL_INPUTS=IMAGE_HEIGHT * IMAGE_WIDHT * CHANNELS

# Load dataset

In [43]:
%%time
X_train_all=np.loadtxt(X_TRAIN_PATH,delimiter=',',dtype=int)


Wall time: 55.1 s


In [44]:
%%time
y_train_all=np.loadtxt(Y_TRAIN_PATH,delimiter=',',dtype=int)

Wall time: 355 ms


In [45]:
X_train_all.shape  # 784 = 28 * 28 * 1  image is greay scale so channel=1

(60000, 784)

In [46]:
y_train_all.shape

(60000,)

In [47]:
%%time
X_test=np.loadtxt(X_TEST_PATH,delimiter=',',dtype=int)

Wall time: 9.12 s


In [48]:
%%time
y_test=np.loadtxt(Y_TEST_PATH,delimiter=',',dtype=int)

Wall time: 83 ms


In [49]:
X_test.shape

(10000, 784)

In [50]:
X_test[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [51]:
y_train_all[0] #labels

5

In [52]:
y_train_all[:5]

array([5, 0, 4, 1, 9])

# Data pre-processing

In [53]:
values=y_train_all[:5]

In [54]:
np.eye(10)[values]   #np.eye() makes 10/10 matrix with diagonal elements=1 

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [55]:
np.eye(12)[8]  

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [56]:
# RE_SCALING image pixels between 0-1
X_train_all, X_test = X_train_all/255.0 , X_test /255.0

In [57]:
X_train_all.shape
X_test.shape


(10000, 784)

In [58]:
X_train_all[1] #values in between 0-1

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [59]:
#one hot encoding ie 3 = [0,0,0,1,0,0,0,0,...]
y_train_all=np.eye(NR_CLASSES)[y_train_all]
y_test=np.eye(NR_CLASSES)[y_test]

In [60]:
y_test.shape

(10000, 10)

In [61]:
y_train_all.shape

(60000, 10)

# creating validation set

In [62]:
X_val=X_train_all[:VALIDATION_SIZE]
y_val=y_train_all[:VALIDATION_SIZE]

X_train=X_train_all[VALIDATION_SIZE:]
y_train=y_train_all[VALIDATION_SIZE:]

In [63]:
X_val.shape

(10000, 784)

In [64]:
X_train.shape

(50000, 784)

In [65]:
X_test.shape

(10000, 784)

## Setup tensorflow graph

In [87]:
# defining hyperparameters

n_epochs=10
learning_rate=0.0001

n_hidden1=512
n_hidden2=64

In [67]:
X = tf.placeholder(tf.float32, shape=[None,TOTAL_INPUTS]) #NONE because size in batches decided later
Y = tf.placeholder(tf.float32, shape=[None,NR_CLASSES])

## setting initial weights and biases for hidden layers

In [68]:
# FOR FIRST HIDDEN LAYER

initial_w1=tf.truncated_normal(shape=[TOTAL_INPUTS,512],stddev=0.1,seed=42)
w1=tf.Variable(initial_value=initial_w1)  #storing weights in tensorflow variable

In [69]:
initial_b1=tf.constant(value=0.0,shape=[n_hidden1])

b1=tf.Variable(initial_value=initial_b1) #storing biases in tensorflow variable

In [70]:
layer1_in = tf.matmul(X , w1) + b1

In [71]:
layer1_out = tf.nn.relu(layer1_in)

In [72]:
# FOR SECOND HIDDEN LAYER

initial_w2=tf.truncated_normal(shape=[n_hidden1,n_hidden2],stddev=0.1,seed=42)
w2=tf.Variable(initial_value=initial_w2)

initial_b2=tf.constant(value=0.0,shape=[n_hidden2])
b2=tf.Variable(initial_value=initial_b2)

layer2_in = tf.matmul(layer1_out, w2) + b2
layer2_out = tf.nn.relu(layer2_in)

In [73]:
# FOR OUTPUT LAYER

initial_w3=tf.truncated_normal(shape=[n_hidden2,NR_CLASSES],stddev=0.1,seed=42)
w3=tf.Variable(initial_value=initial_w3)

initial_b3=tf.constant(value=0.0,shape=[NR_CLASSES])
b3=tf.Variable(initial_value=initial_b3)

layer3_in = tf.matmul(layer2_out, w3) + b3
output = tf.nn.softmax(layer3_in)

# Loss , optimization,accuracy

#### Defining loss function

In [78]:
loss=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=output))

#### Defining optimizer

In [79]:
optimizer=tf.train.AdamOptimizer(learning_rate)
train_step=optimizer.minimize(loss)

#### Defining Accuracy metrics

In [80]:
correct_pred=tf.equal(tf.argmax(output,axis=1),tf.argmax(Y,axis=1))
accuracy=tf.reduce_mean(tf.cast(correct_pred,tf.float32))

## Run session

In [81]:
sess= tf.Session()

In [83]:
init=tf.global_variables_initializer()
sess.run(init)

In [84]:
b1.eval(sess)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [85]:
b3.eval(sess)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

### Batching data

In [88]:
size_of_batch=1000


In [89]:
num_examples = y_train.shape[0]   #50000
nr_iterations = int(num_examples/size_of_batch) #50000/1000=50

index_in_epoch=0   #0-50000

In [90]:
def next_batch(batch_size,data,labels):
    global num_examples
    global index_in_epoch
    
    start = index_in_epoch
    index_in_epoch += size_of_batch
    
    if index_in_epoch > num_examples:  #end of dataset(50000) ,begin next epoch
        start=0
        index_in_epoch=batch_size
    
    end=index_in_epoch
    
    
    return data[start:index_in_epoch],labels[start:index_in_epoch]

### Training loop

In [92]:
for epoch in range(n_epochs):
    for i in range(nr_iterations):
        batch_x,batch_y=next_batch(batch_size=size_of_batch,data=X_train,labels=y_train)
        
        feed_dict={X:batch_x,Y:batch_y}  #feeding dict to session
        
        sess.run(train_step,feed_dict=feed_dict)  #minimise training loss of batch
        
        batch_accuracy=sess.run(fetches=[accuracy],feed_dict=feed_dict)
        
    print(f'Epoch : {epoch} \t | Training accuracy : {batch_accuracy}')
    
print('Done Training')
        
        

Epoch : 0 	 | Training accuracy : [0.551]
Epoch : 1 	 | Training accuracy : [0.721]
Epoch : 2 	 | Training accuracy : [0.828]
Epoch : 3 	 | Training accuracy : [0.899]
Epoch : 4 	 | Training accuracy : [0.933]
Epoch : 5 	 | Training accuracy : [0.946]
Epoch : 6 	 | Training accuracy : [0.949]
Epoch : 7 	 | Training accuracy : [0.953]
Epoch : 8 	 | Training accuracy : [0.958]
Epoch : 9 	 | Training accuracy : [0.961]
Done Training
